# Generated by Django 3.2.13 on 2023-11-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideShare', '0002_vehiclerental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclerental',
            name='checkinLocal',
            field=models.CharField(blank=True, choices=[('Location1', 'West Lawn'), ('Location2', 'Campus Rec Center'), ('Location3', 'The Lodge'), ('Location4', 'University Hall'), ('Location5', 'Location 5')], max_length=200, null=True),
        ),
    ]
