# Generated by Django 3.2.13 on 2023-11-18 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RideShare', '0003_alter_vehiclerental_checkinlocal'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBillingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amountDue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('paymentMethod', models.CharField(default='Credit Card', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
            },
        ),
    ]
