# Generated by Django 4.2.5 on 2023-11-19 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideShare', '0006_remove_vehiclerental_paymentmethod_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='cost',
            new_name='minimumCharge',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='costPerMinute',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=10),
        ),
    ]
